export const catalogSource = {
  version: "2026-06-02-step1",
  metadata: {
    description:
      "Authoritative TF20 catalog source for initial bootstrap and future additive sync updates.",
    policy:
      "Catalog changes are repo-driven, additive by default, and non-destructive for referenced records.",
  },
  roles: [
    {
      key: "pending-user",
      name: "Pending User",
      description: "Guild-verified pending account with limited applicant and recovery access.",
      status: "Active",
      permissionKeys: [
        "accounts.view-self",
        "applications.create-self",
        "applications.view-self",
        "support.create-self",
        "notifications.view-self",
        "notifications.archive-self",
        "access.recovery.request",
      ],
    },
    {
      key: "member",
      name: "Member",
      description: "Active member baseline access.",
      status: "Active",
      permissionKeys: [
        "accounts.view-self",
        "applications.view-self",
        "personnel.view-self",
        "events.view-self",
        "attendance.view-self",
        "loa.create-self",
        "support.create-self",
        "notifications.view-self",
        "notifications.archive-self",
      ],
    },
    {
      key: "recruiter",
      name: "Recruiter",
      description: "Recruiting workflow authority.",
      status: "Active",
      permissionKeys: [
        "accounts.view-self",
        "applications.view-self",
        "personnel.view-self",
        "events.view-self",
        "attendance.view-self",
        "loa.create-self",
        "support.create-self",
        "notifications.view-self",
        "notifications.archive-self",
        "applications.review-recruiter",
      ],
    },
    {
      key: "unit-staff",
      name: "Unit Staff",
      description: "Scoped personnel and workflow authority for unit staff.",
      status: "Active",
      permissionKeys: [
        "accounts.view-self",
        "applications.view-self",
        "personnel.view-self",
        "events.view-self",
        "attendance.view-self",
        "loa.create-self",
        "support.create-self",
        "notifications.view-self",
        "notifications.archive-self",
        "personnel.view-scoped",
        "personnel.update-scoped",
        "applications.review-target-unit",
        "loa.review-scoped",
        "events.manage-scoped",
        "attendance.review-scoped",
        "support.manage-queue",
      ],
    },
    {
      key: "command-staff",
      name: "Command Staff",
      description: "Elevated command oversight authority.",
      status: "Active",
      permissionKeys: [
        "accounts.view-self",
        "applications.view-self",
        "personnel.view-self",
        "events.view-self",
        "attendance.view-self",
        "loa.create-self",
        "support.create-self",
        "notifications.view-self",
        "notifications.archive-self",
        "personnel.view-scoped",
        "personnel.update-scoped",
        "applications.review-target-unit",
        "loa.review-scoped",
        "events.manage-scoped",
        "attendance.review-scoped",
        "support.manage-queue",
        "training.view-scoped",
        "training.record-scoped",
        "serviceRecords.manage-scoped",
        "audit.view",
        "integrations.view",
      ],
    },
    {
      key: "trainer",
      name: "Trainer",
      description: "Training and qualification authority.",
      status: "Active",
      permissionKeys: [
        "accounts.view-self",
        "applications.view-self",
        "personnel.view-self",
        "events.view-self",
        "attendance.view-self",
        "loa.create-self",
        "support.create-self",
        "notifications.view-self",
        "notifications.archive-self",
        "training.view-scoped",
        "training.record-scoped",
      ],
    },
    {
      key: "system-admin",
      name: "System Admin",
      description: "System-wide administration and recovery authority.",
      status: "Active",
      permissionKeys: [
        "accounts.view-self",
        "applications.view-self",
        "personnel.view-self",
        "events.view-self",
        "attendance.view-self",
        "loa.create-self",
        "support.create-self",
        "notifications.view-self",
        "notifications.archive-self",
        "applications.review-recruiter",
        "applications.review-target-unit",
        "personnel.view-scoped",
        "personnel.update-scoped",
        "loa.review-scoped",
        "events.manage-scoped",
        "attendance.review-scoped",
        "training.view-scoped",
        "training.record-scoped",
        "serviceRecords.manage-scoped",
        "support.manage-queue",
        "audit.view",
        "access.recovery.request",
        "access.recovery.review",
        "access.sessions.revoke",
        "access.bootstrap.complete",
        "catalogs.manage",
        "integrations.view",
        "integrations.manage",
      ],
    },
  ],
  permissions: [
    {
      key: "accounts.view-self",
      module: "accounts",
      action: "view-self",
      name: "View Own Account",
      description: "Allows a user to view their own account record.",
      sensitiveCategory: null,
      requiresRecentAuth: false,
      status: "Active",
    },
    {
      key: "access.recovery.request",
      module: "access",
      action: "recovery-request",
      name: "Request Recovery",
      description: "Allows account recovery request submission.",
      sensitiveCategory: "recovery",
      requiresRecentAuth: false,
      status: "Active",
    },
    {
      key: "access.recovery.review",
      module: "access",
      action: "recovery-review",
      name: "Review Recovery",
      description: "Allows review and completion of recovery requests.",
      sensitiveCategory: "recovery",
      requiresRecentAuth: true,
      status: "Active",
    },
    {
      key: "access.sessions.revoke",
      module: "access",
      action: "sessions-revoke",
      name: "Revoke Sessions",
      description: "Allows revocation of account or global sessions.",
      sensitiveCategory: "access-management",
      requiresRecentAuth: true,
      status: "Active",
    },
    {
      key: "access.bootstrap.complete",
      module: "access",
      action: "bootstrap-complete",
      name: "Complete Bootstrap",
      description: "Allows one-time bootstrap completion.",
      sensitiveCategory: "access-management",
      requiresRecentAuth: true,
      status: "Active",
    },
    {
      key: "catalogs.manage",
      module: "catalogs",
      action: "manage",
      name: "Manage Catalogs",
      description: "Allows administrative catalog management.",
      sensitiveCategory: "access-management",
      requiresRecentAuth: true,
      status: "Active",
    },
    {
      key: "applications.create-self",
      module: "applications",
      action: "create-self",
      name: "Create Own Application",
      description: "Allows a pending user to submit their own application.",
      sensitiveCategory: null,
      requiresRecentAuth: false,
      status: "Active",
    },
    {
      key: "applications.view-self",
      module: "applications",
      action: "view-self",
      name: "View Own Application",
      description: "Allows viewing of one's own application records.",
      sensitiveCategory: null,
      requiresRecentAuth: false,
      status: "Active",
    },
    {
      key: "applications.review-recruiter",
      module: "applications",
      action: "review-recruiter",
      name: "Recruiter Review",
      description: "Allows recruiter screening and recommendation actions.",
      sensitiveCategory: null,
      requiresRecentAuth: true,
      status: "Active",
    },
    {
      key: "applications.review-target-unit",
      module: "applications",
      action: "review-target-unit",
      name: "Target Unit Review",
      description: "Allows target-unit application decision actions.",
      sensitiveCategory: null,
      requiresRecentAuth: true,
      status: "Active",
    },
    {
      key: "personnel.view-self",
      module: "personnel",
      action: "view-self",
      name: "View Own Personnel",
      description: "Allows a user to view their own personnel profile.",
      sensitiveCategory: null,
      requiresRecentAuth: false,
      status: "Active",
    },
    {
      key: "personnel.view-scoped",
      module: "personnel",
      action: "view-scoped",
      name: "View Scoped Personnel",
      description: "Allows scoped staff personnel views.",
      sensitiveCategory: null,
      requiresRecentAuth: false,
      status: "Active",
    },
    {
      key: "personnel.update-scoped",
      module: "personnel",
      action: "update-scoped",
      name: "Update Scoped Personnel",
      description: "Allows protected personnel updates within scope.",
      sensitiveCategory: null,
      requiresRecentAuth: true,
      status: "Active",
    },
    {
      key: "events.view-self",
      module: "events",
      action: "view-self",
      name: "View Events",
      description: "Allows viewing of event records relevant to the account.",
      sensitiveCategory: null,
      requiresRecentAuth: false,
      status: "Active",
    },
    {
      key: "events.manage-scoped",
      module: "events",
      action: "manage-scoped",
      name: "Manage Scoped Events",
      description: "Allows scoped event creation and management.",
      sensitiveCategory: null,
      requiresRecentAuth: true,
      status: "Active",
    },
    {
      key: "attendance.view-self",
      module: "attendance",
      action: "view-self",
      name: "View Own Attendance",
      description: "Allows viewing of one's own attendance records.",
      sensitiveCategory: null,
      requiresRecentAuth: false,
      status: "Active",
    },
    {
      key: "attendance.review-scoped",
      module: "attendance",
      action: "review-scoped",
      name: "Review Scoped Attendance",
      description: "Allows scoped attendance review and correction.",
      sensitiveCategory: null,
      requiresRecentAuth: true,
      status: "Active",
    },
    {
      key: "loa.create-self",
      module: "loa",
      action: "create-self",
      name: "Create Own LOA",
      description: "Allows submission of one's own LOA request.",
      sensitiveCategory: "private-loa",
      requiresRecentAuth: false,
      status: "Active",
    },
    {
      key: "loa.review-scoped",
      module: "loa",
      action: "review-scoped",
      name: "Review Scoped LOA",
      description: "Allows scoped LOA review and decision actions.",
      sensitiveCategory: "private-loa",
      requiresRecentAuth: true,
      status: "Active",
    },
    {
      key: "training.view-scoped",
      module: "training",
      action: "view-scoped",
      name: "View Scoped Training",
      description: "Allows viewing of scoped training and qualification records.",
      sensitiveCategory: null,
      requiresRecentAuth: false,
      status: "Active",
    },
    {
      key: "training.record-scoped",
      module: "training",
      action: "record-scoped",
      name: "Record Scoped Training",
      description: "Allows recording of scoped training completions and statuses.",
      sensitiveCategory: null,
      requiresRecentAuth: true,
      status: "Active",
    },
    {
      key: "serviceRecords.manage-scoped",
      module: "serviceRecords",
      action: "manage-scoped",
      name: "Manage Scoped Service Records",
      description: "Allows scoped promotions, awards, and protected service records.",
      sensitiveCategory: "disciplinary",
      requiresRecentAuth: true,
      status: "Active",
    },
    {
      key: "support.create-self",
      module: "support",
      action: "create-self",
      name: "Create Own Support Ticket",
      description: "Allows a user to create their own support tickets.",
      sensitiveCategory: null,
      requiresRecentAuth: false,
      status: "Active",
    },
    {
      key: "support.manage-queue",
      module: "support",
      action: "manage-queue",
      name: "Manage Support Queue",
      description: "Allows assignment and workflow management for support tickets.",
      sensitiveCategory: null,
      requiresRecentAuth: true,
      status: "Active",
    },
    {
      key: "audit.view",
      module: "audit",
      action: "view",
      name: "View Audit",
      description: "Allows viewing of audit logs.",
      sensitiveCategory: "audit",
      requiresRecentAuth: true,
      status: "Active",
    },
    {
      key: "notifications.view-self",
      module: "notifications",
      action: "view-self",
      name: "View Own Notifications",
      description: "Allows a user to view their own in-app notifications.",
      sensitiveCategory: null,
      requiresRecentAuth: false,
      status: "Active",
    },
    {
      key: "notifications.archive-self",
      module: "notifications",
      action: "archive-self",
      name: "Archive Own Notifications",
      description: "Allows a user to archive their own in-app notifications.",
      sensitiveCategory: null,
      requiresRecentAuth: false,
      status: "Active",
    },
    {
      key: "integrations.view",
      module: "integrations",
      action: "view",
      name: "View Integrations",
      description: "Allows viewing of integration state and logs.",
      sensitiveCategory: "integration",
      requiresRecentAuth: true,
      status: "Active",
    },
    {
      key: "integrations.manage",
      module: "integrations",
      action: "manage",
      name: "Manage Integrations",
      description: "Allows management of integration-related operations.",
      sensitiveCategory: "integration",
      requiresRecentAuth: true,
      status: "Active",
    },
  ],
  units: [
    {
      code: "TF20",
      name: "Task Force 20",
      type: "Task Force",
      parentCode: null,
      status: "Active",
      sortOrder: 0,
    },
    {
      code: "TF20-RANGER-A",
      name: "A Co, 1/75th Ranger Regiment",
      type: "Unit",
      parentCode: "TF20",
      status: "Active",
      sortOrder: 10,
    },
    {
      code: "TF20-SFOD-A1",
      name: "1 Troop, A Squadron, 1st SFOD-Delta",
      type: "Unit",
      parentCode: "TF20",
      status: "Active",
      sortOrder: 20,
    },
    {
      code: "TF20-SOAR-B160",
      name: "B Co, 2/160th SOAR",
      type: "Unit",
      parentCode: "TF20",
      status: "Active",
      sortOrder: 30,
    },
  ],
  ranks: [
    { code: "COL", name: "Colonel", abbreviation: "COL", category: "Officer", sortOrder: 10, status: "Active" },
    { code: "CPT", name: "Captain", abbreviation: "CPT", category: "Officer", sortOrder: 20, status: "Active" },
    { code: "1LT", name: "First Lieutenant", abbreviation: "1LT", category: "Officer", sortOrder: 30, status: "Active" },
    { code: "CW3", name: "Chief Warrant Officer 3", abbreviation: "CW3", category: "Warrant Officer", sortOrder: 40, status: "Active" },
    { code: "SGM", name: "Sergeant Major", abbreviation: "SGM", category: "Enlisted", sortOrder: 50, status: "Active" },
    { code: "MSG", name: "Master Sergeant", abbreviation: "MSG", category: "Enlisted", sortOrder: 60, status: "Active" },
    { code: "SFC", name: "Sergeant First Class", abbreviation: "SFC", category: "Enlisted", sortOrder: 70, status: "Active" },
    { code: "SSG", name: "Staff Sergeant", abbreviation: "SSG", category: "Enlisted", sortOrder: 80, status: "Active" },
    { code: "SGT", name: "Sergeant", abbreviation: "SGT", category: "Enlisted", sortOrder: 90, status: "Active" },
    { code: "SPC", name: "Specialist", abbreviation: "SPC", category: "Enlisted", sortOrder: 100, status: "Active" },
    { code: "PFC", name: "Private First Class", abbreviation: "PFC", category: "Enlisted", sortOrder: 110, status: "Active" },
    { code: "PV2", name: "Private", abbreviation: "PV2", category: "Enlisted", sortOrder: 120, status: "Active" },
  ],
  staffSections: [
    {
      code: "J2",
      name: "J2",
      description: "Intelligence staff section.",
      status: "Active",
    },
  ],
  specialties: [
    { code: "11A", name: "Infantry Officer", category: "Infantry", status: "Active" },
    { code: "11B", name: "Infantryman", category: "Infantry", status: "Active" },
    { code: "12B", name: "Combat Engineer", category: "Engineer", status: "Active" },
    { code: "13F", name: "Joint Fire Support Specialist", category: "Fires", status: "Active" },
    { code: "25C", name: "Radio Operator", category: "Signal", status: "Active" },
    { code: "68W", name: "Combat Medic", category: "Medical", status: "Active" },
    {
      code: "153A",
      name: "Special Operations Rotary Wing Aviator",
      category: "Aviation",
      status: "Active",
    },
    { code: "18A", name: "Special Forces Officer", category: "Special Forces", status: "Active" },
    {
      code: "18B",
      name: "Special Forces Weapons Sergeant",
      category: "Special Forces",
      status: "Active",
    },
    {
      code: "18Z",
      name: "Special Forces Operations Sergeant",
      category: "Special Forces",
      status: "Active",
    },
  ],
  billets: [
    { code: "RANGER-COMPANY-COMMANDER", unitCode: "TF20-RANGER-A", name: "Company Commander", category: "Command", status: "Active" },
    { code: "RANGER-1PLT-PL", unitCode: "TF20-RANGER-A", name: "1PLT PL", category: "Leadership", status: "Active" },
    { code: "RANGER-1PLT-RTO", unitCode: "TF20-RANGER-A", name: "1PLT RTO", category: "Support", status: "Active" },
    { code: "RANGER-1PLT-ASST-MEDIC", unitCode: "TF20-RANGER-A", name: "1PLT Asst Medic", category: "Medical", status: "Active" },
    { code: "RANGER-1PLT-ENGINEER", unitCode: "TF20-RANGER-A", name: "1PLT Engineer", category: "Engineer", status: "Active" },
    { code: "RANGER-1PLT-JTAC", unitCode: "TF20-RANGER-A", name: "1PLT JTAC", category: "Fires", status: "Active" },
    { code: "RANGER-1PLT-MEDIC", unitCode: "TF20-RANGER-A", name: "1PLT Medic", category: "Medical", status: "Active" },
    { code: "RANGER-1PLT-1SQD-SL", unitCode: "TF20-RANGER-A", name: "1PLT, 1SQD SL", category: "Leadership", status: "Active" },
    { code: "RANGER-1PLT-1SQD-A-AUTORIFLEMAN", unitCode: "TF20-RANGER-A", name: "1PLT, 1SQD, A, AutoRifleman", category: "Rifle", status: "Active" },
    { code: "RANGER-1PLT-1SQD-A-GRENADIER", unitCode: "TF20-RANGER-A", name: "1PLT, 1SQD, A, Grenadier", category: "Rifle", status: "Active" },
    { code: "RANGER-1PLT-1SQD-A-RIFLEMAN", unitCode: "TF20-RANGER-A", name: "1PLT, 1SQD, A, Rifleman", category: "Rifle", status: "Active" },
    { code: "RANGER-1PLT-1SQD-A-TL", unitCode: "TF20-RANGER-A", name: "1PLT, 1SQD, A, TL", category: "Leadership", status: "Active" },
    { code: "RANGER-1PLT-1SQD-B-RIFLEMAN", unitCode: "TF20-RANGER-A", name: "1PLT, 1SQD, B, Rifleman", category: "Rifle", status: "Active" },
    { code: "RANGER-1PLT-1SQD-B-TL", unitCode: "TF20-RANGER-A", name: "1PLT, 1SQD, B, TL", category: "Leadership", status: "Active" },
    { code: "SFOD-CO", unitCode: "TF20-SFOD-A1", name: "CO", category: "Command", status: "Active" },
    { code: "SFOD-TL", unitCode: "TF20-SFOD-A1", name: "TL", category: "Leadership", status: "Active" },
    { code: "SFOD-ATL-PM", unitCode: "TF20-SFOD-A1", name: "ATL/Precision Marksman", category: "Leadership", status: "Active" },
    { code: "SFOD-ASSAULTER-BREACHER", unitCode: "TF20-SFOD-A1", name: "Assaulter/Breacher", category: "Assaulter", status: "Active" },
    { code: "SFOD-ASSAULTER-GAY-CANADIAN", unitCode: "TF20-SFOD-A1", name: "Assaulter/Gay Canadian", category: "Assaulter", status: "Active" },
    { code: "SFOD-ASSAULTER-PM", unitCode: "TF20-SFOD-A1", name: "Assaulter/Precision Marksman", category: "Assaulter", status: "Active" },
    { code: "SFOD-HWO", unitCode: "TF20-SFOD-A1", name: "Heavy Weapons Operator", category: "Weapons", status: "Active" },
    { code: "SOAR-CO", unitCode: "TF20-SOAR-B160", name: "Commanding Officer", category: "Command", status: "Active" },
    { code: "SOAR-XO", unitCode: "TF20-SOAR-B160", name: "Executive Officer", category: "Command", status: "Active" },
    { code: "SOAR-AVIATOR", unitCode: "TF20-SOAR-B160", name: "Aviator", category: "Flight", status: "Active" },
    { code: "SOAR-AIR-CREW", unitCode: "TF20-SOAR-B160", name: "Air Crew Member", category: "Flight", status: "Active" },
  ],
  trainingCourses: [],
  qualifications: [],
  awards: [],
};
